Calamity/Calamity/Controllers/AudioPlayerController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Calamity.Extensions;

namespace Calamity.Controllers
{
    public class AudioPlayerController : Controller
    {
        //
        // GET: /AudioPlayer/

        public ActionResult GetFile(String name)
        {
           // string filePath = Server.MapPath(Url.Content(name));

            return new VideoResult(new FileInfo(name)); 
            //File(filePath, "application/octet-stream", filePath);
        }

        public ActionResult PlaySong(Object model)
        {
            return View();
        }

        public ActionResult PlaySongs(Object model)
        {
            return View();
        }

        public ActionResult EmptyAudioPlayer(String name)
        {
            ViewBag.AudioName = name;
            return View();
        }
    }
}

Calamity/Calamity/Controllers/VideoPlayerController.cs
using Lib.Web.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Calamity.Extensions;

namespace Calamity.Controllers
{
    public class VideoPlayerController : Controller
    {
        //
        // GET: /VideoPlayer/

        public ActionResult PlayVideo(String name)
        {
            ViewBag.VideoName = name;
            return View();
        }

        public ActionResult EmptyVideoPlayer()
        {
            return View();
        }

        public ActionResult Video(String type, String name)
        {
            FileInfo oceansClipInfo = null;
            string oceansClipMimeType = String.Format("video/{0}", type);

            switch (type)
            {
                case "mp4":
                    //oceansClipInfo = new FileInfo(Server.MapPath(String.Format("~/Content/video/{0}.mp4",name)));
                    oceansClipInfo = new FileInfo(name);
                    break;
                case "webm":
                    oceansClipInfo = new FileInfo(Server.MapPath(String.Format("~/Content/video/{0}.webm", name)));
                    break;
                case "ogg":
                    oceansClipInfo = new FileInfo(Server.MapPath(String.Format("~/Content/video/{0}.ogg", name)));
                    break;
            }

            return new RangeFilePathResult(oceansClipMimeType, oceansClipInfo.FullName, oceansClipInfo.LastWriteTimeUtc, oceansClipInfo.Length);
            
        }
    }
}

Calamity/Calamity/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    @RenderSection("Css", false)
    <script src="@Url.Content("~/Scripts/jquery-2.0.3.min.js")" type="text/javascript"></script>
    @RenderSection("Script", false)
    <!-- We use Backloads. bundeling feature to register all client side javascript and style files of the jQuery File Upload Plugin  -->
        @Styles.Render("~/bundles/fileupload/jqueryui/BasicPlusUI/css")
        @RenderSection("styles", required: false)
    <!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
</head>
<body>
    <div class="page">
        <div id="header">
            <div id="title">
                <h1>
                    <a href="@Url.Action("Index", "Home")" class="logo">Calamity</a>

                </h1>
            </div>
            <div id="logindisplay">
                @{Html.RenderAction("LogOnPartial", "Account");}
            </div>
            <div id="menucontainer">
                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @if (Request.IsAuthenticated)
                    {
                        <li> @Html.ActionLink("Change password","ChangePassword","Account")</li>
                        <li> @Html.ActionLink("File Browser","Browse","Browser")</li>
                        <li> @Html.ActionLink("Video player","EmptyVideoPlayer","VideoPlayer")</li>
                        <li> @Html.ActionLink("Audio player","EmptyAudioPlayer","AudioPlayer")</li>
                        <li> @Html.ActionLink("Reader","EmptyReader","Reader")</li>
                    }
                </ul>
            </div>
        </div>
        <div id="main">
            @RenderBody()
        </div>
        <div id="footer">
            Copyright &copy; 1992-2013 Cubi, capo
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/jqueryui")
        <!-- We use Backloads. bundeling feature to register all client side javascript and style files of the jQuery File Upload Plugin  -->
        @Scripts.Render("~/bundles/fileupload/jqueryui/BasicPlusUI/js")
        @RenderSection("scripts", required: false)
</body>
</html>

Calamity/Calamity/Views/Shared/_LogOnPartial.cshtml
@model Calamity.Models.LogOnModel

@if (Request.IsAuthenticated)
{
    <text>Hello: <strong>@User.Identity.Name</strong>
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
}
else
{
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

    @Html.ValidationSummary(true, "Login was unsuccessful. Please correct the errors and try again.")

    using (Html.BeginForm("LogOn", "Account"))
    {
    <div>
        <fieldset id="logon-field">
            <legend>Login</legend>
            <div>
                    @Html.LabelFor(x => x.UserName, new {@class = "login-label" })
                    @Html.TextBoxFor(x => x.UserName, new {@class = "login-field" })
            </div>
            <div>
                @Html.ValidationMessageFor(m => m.UserName)
            </div>
            <div>
                    @Html.LabelFor(m => m.Password, new {@class = "login-label" })
                    @Html.PasswordFor(m => m.Password, new {@class = "login-field" })
            </div>
            <div>
                @Html.ValidationMessageFor(m => m.Password)
            </div>
            <div>
                    Don't have an account yet? @Html.ActionLink("Register now.", "Register", "Account")
            </div>
            <div>
                    @Html.CheckBoxFor(m => m.RememberMe)
                    @Html.LabelFor(m => m.RememberMe, new {@class = "login-label" })
                <div class="login-field">
                    <input type="submit" value="Login" />
                </div>
            </div>
            <div>
                
            </div>
        </fieldset>
    </div>
    }
}